-- V-POINTS 2.0 isolated foundation
-- Draft only: do not run against production until reviewed/tested.
-- Prefix keeps V2 separate from current V-POINTS/V-SCORE tables.

create table if not exists public.vp2_regions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_branches (
  id bigint generated by default as identity primary key,
  region_id bigint references public.vp2_regions(id),
  name text not null,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  unique(region_id,name)
);

create table if not exists public.vp2_profiles (
  id uuid primary key default gen_random_uuid(),
  employee_id text unique,
  full_name text not null,
  position text,
  function_name text,
  employment_type text not null default 'VARDA COMPANY EMPLOYEE',
  agency_name text,
  branch_id bigint references public.vp2_branches(id),
  region_id bigint references public.vp2_regions(id),
  employment_status text not null default 'PENDING ACTIVATION',
  photo_path text,
  hired_or_deployed_on date,
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vp2_management_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  profile_id uuid references public.vp2_profiles(id),
  username text not null unique,
  role_code text not null,
  function_name text,
  scope_type text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_user_branch_assignments (
  user_id uuid references public.vp2_management_users(user_id) on delete cascade,
  branch_id bigint references public.vp2_branches(id) on delete cascade,
  primary key(user_id,branch_id)
);

create table if not exists public.vp2_user_region_assignments (
  user_id uuid references public.vp2_management_users(user_id) on delete cascade,
  region_id bigint references public.vp2_regions(id) on delete cascade,
  primary key(user_id,region_id)
);

create table if not exists public.vp2_point_ledger (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.vp2_profiles(id),
  transaction_type text not null,
  points integer not null,
  source_type text not null,
  source_id text,
  reason text not null,
  posted_by uuid references auth.users(id),
  reverses_ledger_id bigint references public.vp2_point_ledger(id),
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_leader_activity (
  id bigint generated by default as identity primary key,
  leader_user_id uuid not null references public.vp2_management_users(user_id),
  activity_type text not null,
  subject_profile_id uuid references public.vp2_profiles(id),
  meaningful boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Baseline is represented by a ledger transaction at activation, not an editable balance.
-- V2 app calculates: baseline + merits - validated deductions + reversals.

alter table public.vp2_regions enable row level security;
alter table public.vp2_branches enable row level security;
alter table public.vp2_profiles enable row level security;
alter table public.vp2_management_users enable row level security;
alter table public.vp2_user_branch_assignments enable row level security;
alter table public.vp2_user_region_assignments enable row level security;
alter table public.vp2_point_ledger enable row level security;
alter table public.vp2_leader_activity enable row level security;
alter table public.vp2_audit_log enable row level security;

-- Intentionally no permissive policies in this draft.
-- Access stays denied until exact role/scope RLS policies are reviewed and added.