-- V-POINTS 2.0 workflow layer
-- DEVELOPMENT ONLY. Depends on supabase/v2_schema.sql.
-- Do not run against production until scope/RLS review is complete.

create table if not exists public.vp2_policies (
  id bigint generated by default as identity primary key,
  act_code text not null unique,
  title text not null,
  department text,
  rule_text text,
  severity text,
  points integer,
  evidence_guidance text,
  due_process text,
  legacy_approval text,
  mapped_route jsonb not null default '{}'::jsonb,
  keywords text,
  basis text,
  source_version text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vp2_merits (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.vp2_profiles(id),
  merit_type text not null,
  requested_points integer not null,
  reason text not null,
  status text not null default 'PENDING',
  submitted_by uuid not null references auth.users(id),
  approved_by uuid references auth.users(id),
  approved_at timestamptz,
  ledger_id bigint references public.vp2_point_ledger(id),
  created_at timestamptz not null default now(),
  constraint vp2_no_self_merit_submit check (profile_id is not null)
);

create sequence if not exists public.vp2_case_number_seq start 1;
create table if not exists public.vp2_cases (
  id uuid primary key default gen_random_uuid(),
  case_number text not null unique default ('VP-' || to_char(current_date,'YYYY') || '-' || lpad(nextval('public.vp2_case_number_seq')::text,6,'0')),
  profile_id uuid not null references public.vp2_profiles(id),
  branch_id bigint references public.vp2_branches(id),
  region_id bigint references public.vp2_regions(id),
  category text not null,
  policy_id bigint references public.vp2_policies(id),
  incident_date timestamptz,
  location_text text,
  description text not null,
  status text not null default 'PENDING',
  hr_outcome text,
  final_point_effect integer,
  submitted_by uuid not null references auth.users(id),
  closed_by uuid references auth.users(id),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.vp2_evidence (
  id uuid primary key default gen_random_uuid(),
  case_id uuid references public.vp2_cases(id) on delete restrict,
  merit_id uuid references public.vp2_merits(id) on delete restrict,
  evidence_type text not null,
  private_path text not null,
  thumbnail_path text,
  remarks text,
  review_status text,
  submitted_in_error boolean not null default false,
  replacement_evidence_id uuid references public.vp2_evidence(id),
  uploaded_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  constraint vp2_evidence_one_parent check ((case_id is not null) <> (merit_id is not null))
);

create table if not exists public.vp2_case_actions (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.vp2_cases(id) on delete restrict,
  action_type text not null,
  outcome text,
  remarks text,
  actor_user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_signoffs (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id uuid not null,
  required_role text not null,
  decision text,
  remarks text,
  reviewer_user_id uuid references auth.users(id),
  decided_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_appraisals (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.vp2_profiles(id),
  appraiser_profile_id uuid references public.vp2_profiles(id),
  appraiser_user_id uuid not null references auth.users(id),
  period_start date,
  period_end date,
  rating text,
  summary text,
  status text not null default 'DRAFT',
  merit_eligible boolean not null default false,
  merit_id uuid references public.vp2_merits(id),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.vp2_acknowledgements (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.vp2_profiles(id),
  policy_version text not null,
  acknowledged_at timestamptz not null,
  source_reference text,
  created_at timestamptz not null default now()
);

create table if not exists public.vp2_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null,
  title text not null,
  body text,
  target_type text,
  target_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.vp2_policies enable row level security;
alter table public.vp2_merits enable row level security;
alter table public.vp2_cases enable row level security;
alter table public.vp2_evidence enable row level security;
alter table public.vp2_case_actions enable row level security;
alter table public.vp2_signoffs enable row level security;
alter table public.vp2_appraisals enable row level security;
alter table public.vp2_acknowledgements enable row level security;
alter table public.vp2_notifications enable row level security;

-- RLS policies are intentionally NOT permissive here.
-- Next gate: reviewed helper functions + exact Executive/National/Regional/Branch scope policies.
-- Evidence paths are references to PRIVATE storage only; never public URLs.
